name: calendar_carousel
description: A lightweight and highly customizable calendar view for your Flutter app.
version: 0.1.0-nullsafety.2
homepage: https://github.com/zhengbomo/calendarcarousel

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  stateful_builder_controller: ^0.1.0-nullsafety.1


dev_dependencies:
  flutter_test:
    sdk: flutter