name: calendar_carousel
description: A lightweight and highly customizable calendar view for your Flutter app.
version: 0.0.9
homepage: https://github.com/zhengbomo/calendarcarousel

environment:
  sdk: ">=2.7.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  stateful_builder_controller: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter